data2model_map:
  connections:
    (('4', 'Pvalb'), ('4', 'Pvalb')):
      source_data:
        airavata_cerebrum.dataset.ai_synphys:
          label: AI Syn Phys
          workflow:
          - exec_params:
              post: L4-Pvalb
              pre: L4-Pvalb
            init_params: {}
            label: Filter by Pair
            name: airavata_cerebrum.operations.ai_synphys.AISynPhysPairFilter
            type: xform
    (('4', 'Pvalb'), ('4', 'Sst')):
      source_data:
        airavata_cerebrum.dataset.ai_synphys:
          label: AI Syn Phys
          workflow:
          - exec_params:
              post: L4-Sst
              pre: L4-Pvalb
            init_params: {}
            label: Filter by Pair
            name: airavata_cerebrum.operations.ai_synphys.AISynPhysPairFilter
            type: xform
    (('4', 'Pvalb'), ('4', 'Vip')):
      source_data:
        airavata_cerebrum.dataset.ai_synphys:
          label: AI Syn Phys
          workflow:
          - exec_params:
              post: L4-Vip
              pre: L4-Pvalb
            init_params: {}
            label: Filter by Pair
            name: airavata_cerebrum.operations.ai_synphys.AISynPhysPairFilter
            type: xform
    (('4', 'Sst'), ('4', 'Pvalb')):
      source_data:
        airavata_cerebrum.dataset.ai_synphys:
          label: AI Syn Phys
          workflow:
          - exec_params:
              post: L4-Pvalb
              pre: L4-Sst
            init_params: {}
            label: Filter by Pair
            name: airavata_cerebrum.operations.ai_synphys.AISynPhysPairFilter
            type: xform
    (('4', 'Sst'), ('4', 'Sst')):
      source_data:
        airavata_cerebrum.dataset.ai_synphys:
          label: AI Syn Phys
          workflow:
          - exec_params:
              post: L4-Sst
              pre: L4-Sst
            init_params: {}
            label: Filter by Pair
            name: airavata_cerebrum.operations.ai_synphys.AISynPhysPairFilter
            type: xform
    (('4', 'Sst'), ('4', 'Vip')):
      source_data:
        airavata_cerebrum.dataset.ai_synphys:
          label: AI Syn Phys
          workflow:
          - exec_params:
              post: L4-Vip
              pre: L4-Sst
            init_params: {}
            label: Filter by Pair
            name: airavata_cerebrum.operations.ai_synphys.AISynPhysPairFilter
            type: xform
    (('4', 'Vip'), ('4', 'Pvalb')):
      source_data:
        airavata_cerebrum.dataset.ai_synphys:
          label: AI Syn Phys
          workflow:
          - exec_params:
              post: L4-Pvalb
              pre: L4-Vip
            init_params: {}
            label: Filter by Pair
            name: airavata_cerebrum.operations.ai_synphys.AISynPhysPairFilter
            type: xform
    (('4', 'Vip'), ('4', 'Sst')):
      source_data:
        airavata_cerebrum.dataset.ai_synphys:
          label: AI Syn Phys
          workflow:
          - exec_params:
              post: L4-Sst
              pre: L4-Vip
            init_params: {}
            label: Filter by Pair
            name: airavata_cerebrum.operations.ai_synphys.AISynPhysPairFilter
            type: xform
    (('4', 'Vip'), ('4', 'Vip')):
      source_data:
        airavata_cerebrum.dataset.ai_synphys:
          label: AI Syn Phys
          workflow:
          - exec_params:
              post: L4-Vip
              pre: L4-Vip
            init_params: {}
            label: Filter by Pair
            name: airavata_cerebrum.operations.ai_synphys.AISynPhysPairFilter
            type: xform
  locations:
    VISp4:
      ('4', 'Pvalb'):
        property_map:
          ei: i
        source_data:
          airavata_cerebrum.dataset.abc_mouse:
            label: Brain Atlas:Cell Fraction
            workflow:
            - exec_params:
                cell_type: Pvalb
                region: VISp4
              init_params: {}
              label: Select Region/Type
              name: airavata_cerebrum.operations.abc_mouse.ABCDbMERFISH_CCFFractionFilter
              type: xform
          airavata_cerebrum.dataset.abm_celltypes:
            label: Cell Types DB:Filter
            workflow:
            - exec_params:
                key: ct
                line: Pvalb-IRES
                reporter_status: positive
              init_params: {}
              label: Select Line
              name: airavata_cerebrum.operations.abm_celltypes.CTPropertyFilter
              type: xform
      ('4', 'Rorb'):
        property_map:
          ei: e
        source_data:
          airavata_cerebrum.dataset.abc_mouse:
            label: Brain Atlas:Cell Fraction
            workflow:
            - exec_params:
                cell_type: IT
                region: VISp4
              init_params: {}
              label: Select Region/Type
              name: airavata_cerebrum.operations.abc_mouse.ABCDbMERFISH_CCFFractionFilter
              type: xform
          airavata_cerebrum.dataset.abm_celltypes:
            label: Cell Types DB:Filter
            workflow:
            - exec_params:
                key: ct
                line: Rorb
                reporter_status: positive
              init_params: {}
              label: Select Line
              name: airavata_cerebrum.operations.abm_celltypes.CTPropertyFilter
              type: xform
      ('4', 'Scnn1a'):
        property_map:
          ei: e
        source_data:
          airavata_cerebrum.dataset.abc_mouse:
            label: Brain Atlas:Cell Fraction
            workflow:
            - exec_params:
                cell_type: IT
                region: VISp4
              init_params: {}
              label: Select Region/Type
              name: airavata_cerebrum.operations.abc_mouse.ABCDbMERFISH_CCFFractionFilter
              type: xform
          airavata_cerebrum.dataset.abm_celltypes:
            label: Cell Types DB:Filter
            workflow:
            - exec_params:
                key: ct
                line: Scnn1a
                reporter_status: positive
              init_params: {}
              label: Select Line
              name: airavata_cerebrum.operations.abm_celltypes.CTPropertyFilter
              type: xform
      ('4', 'Sst'):
        property_map:
          ei: i
        source_data:
          airavata_cerebrum.dataset.abc_mouse:
            label: Brain Atlas:Cell Fraction
            workflow:
            - exec_params:
                cell_type: Pvalb
                region: VISp4
              init_params: {}
              label: Select Region/Type
              name: airavata_cerebrum.operations.abc_mouse.ABCDbMERFISH_CCFFractionFilter
              type: xform
          airavata_cerebrum.dataset.abm_celltypes:
            label: Cell Types DB:Filter
            workflow:
            - exec_params:
                key: ct
                line: Sst
                reporter_status: positive
              init_params: {}
              label: Select Line
              name: airavata_cerebrum.operations.abm_celltypes.CTPropertyFilter
              type: xform
      ('4', 'Vip'):
        property_map:
          ei: i
        source_data:
          airavata_cerebrum.dataset.abc_mouse:
            label: Brain Atlas:Cell Fraction
            workflow:
            - exec_params:
                cell_type: Vip
                region: VISp4
              init_params: {}
              label: Select Region/Type
              name: airavata_cerebrum.operations.abc_mouse.ABCDbMERFISH_CCFFractionFilter
              type: xform
          airavata_cerebrum.dataset.abm_celltypes:
            label: Cell Types DB:Filter
            workflow:
            - exec_params:
                key: ct
                line: Vip-
                reporter_status: positive
              init_params: {}
              label: Select Line
              name: airavata_cerebrum.operations.abm_celltypes.CTPropertyFilter
              type: xform
      property_map:
        neurons:
        - ('4', 'Scnn1a')
        - ('4', 'Rorb')
        - ('4', 'Vip')
        - ('4', 'Pvalb')
        - ('4', 'Sst')
        source_data:
          airavata_cerebrum.dataset.abc_mouse:
            label: Region Filters
            workflow:
            - exec_params:
                region: VISp4
              init_params: {}
              label: Select Region
              name: airavata_cerebrum.operations.abc_mouse.ABCDbMERFISH_CCFFractionFilter
              type: xform
source_data:
  airavata_cerebrum.dataset.abc_mouse:
    db_connect:
      label: Query Allen Brain Cell Atlas
      workflow:
      - exec_params:
          region:
          - VISp
        init_params:
          download_base: ./cache/abc_mouse/
        label: Query ABC MERFISH dataset
        name: airavata_cerebrum.dataset.abc_mouse.ABCDbMERFISH_CCFQuery
        type: query
    label: Allen Brain Cell Atlas
    post_ops:
      label: Filter ABC by Region
      workflow:
      - exec_params:
          region: VISp
          sub_region: VISp4
        init_params: {}
        label: Region filter
        name: airavata_cerebrum.operations.abc_mouse.ABCDbMERFISH_CCFLayerRegionFilter
        type: xform
  airavata_cerebrum.dataset.abm_celltypes:
    db_connect:
      label: Query Allen Cell Types Databse
      workflow:
      - exec_params:
          species: Mus musculus
        init_params: {}
        label: Query w. CT API
        name: airavata_cerebrum.dataset.abm_celltypes.CTDbCellApiQuery
        type: query
      - exec_params:
          jupyter: true
        init_params: {}
        label: Progress Bar
        name: airavata_cerebrum.operations.xform.TQDMWrapper
        type: xform
      - exec_params:
          layer: '4'
          region: VISp
        init_params: {}
        label: Filter by Layer
        name: airavata_cerebrum.operations.abm_celltypes.CTPropertyFilter
        type: xform
      - exec_params:
          first: true
          key: specimen__id
        init_params: {}
        label: Query GLIF Models
        name: airavata_cerebrum.dataset.abm_celltypes.CTDbGlifApiQuery
        type: query
    label: Allen Cell Types Databse
    post_ops:
      label: Filter GLIF Models w. Explained Variance
      workflow:
      - exec_params:
          name: 3 LIF + Afterspike Currents
        init_params: {}
        label: Filter 3 LIF Models
        name: airavata_cerebrum.operations.abm_celltypes.CTModelNameFilter
        type: xform
      - exec_params:
          ratio: 0.7
        init_params: {}
        label: Filter Explained variance
        name: airavata_cerebrum.operations.abm_celltypes.CTExplainedRatioFilter
        type: xform
      - exec_params:
          output_dir: v1l4/components/point_neuron_models/
          suffix: _glif_lif_asc_config.json
        init_params: {}
        label: ABM Model Download
        name: airavata_cerebrum.dataset.abm_celltypes.CTDbGlifApiModelConfigQry
        type: query
  airavata_cerebrum.dataset.ai_synphys:
    db_connect:
      label: Query Allen Syn Phys Database
      workflow:
      - exec_params:
          layer:
          - L4
        init_params:
          download_base: ./cache/ai_synphys/
        label: AI Syn. Phys. Query
        name: airavata_cerebrum.dataset.ai_synphys.AISynPhysQuery
        type: query
    label: AI Syn Phys
    post_ops:
      workflow: []
