channels:
  - conda-forge

dependencies:
  # Python version and pip
  - python=3.10
  - pip

  # Requirements for airavata cerebrum
  - jupyter
  - leidenalg
  - nest-simulator
  - marimo
  - mpi4py
  - openmpi-mpicc
  - pyarrow
  - python-dateutil
  - python-igraph

  # PIP dependencies
  - pip:
      - bmtk
      - parse
      - psutil
      #- https://test-files.pythonhosted.org/packages/c1/67/3ed99ff1afcd2f39c167a1519d4f8d1ce885ea1a6048dc8af1f42d05c896/airavata_cerebrum-0.1.0-py3-none-any.whl
